package orchestrator

import (
	"fmt"
	"time"

	"github.com/Mayveskii/Mimic/internal/cgo"
)

// Plan describes a multi-step operation sequence generated by an LLM.
type Plan struct {
	ID          string              `json:"id"`
	Goal        string              `json:"goal"`
	Steps       []PlanStep          `json:"steps"`
	EstimatedCost   CostEstimate  `json:"estimated_cost"`
	Status      string              `json:"status"` // pending | validated | executing | completed | failed
}

type PlanStep struct {
	OpCode      string                 `json:"opcode"`
	Arguments   map[string]interface{} `json:"arguments"`
	Invariant   string                 `json:"invariant"` // expected outcome
	RollbackOp  string                 `json:"rollback_op,omitempty"`
}

type CostEstimate struct {
	Tokens  int `json:"tokens"`
	TimeUs  int `json:"time_us"`
	MemoryB int `json:"memory_b"`
}

// ConflictMatrix defines which operations cannot run together.
// Borrowed from embryo/pkg/do/
var ConflictMatrix = map[string][]string{
	"SYS_EXEC":      {"BUILD_COMPILE", "BUILD_DEPLOY", "PROC_SPAWN"},
	"BUILD_DEPLOY":  {"BUILD_COMPILE", "SYS_EXEC"},
	"PROC_KILL":     {"PROC_SPAWN"},
	"GIT_COMMIT":    {"GIT_RESET", "GIT_CHECKOUT"},
	"FILE_EDIT":     {"FILE_EDIT"}, // same-file sequential only
}

// ValidatePlan checks a generated plan against:
// 1. Conflict matrix (no incompatible operations in parallel)
// 2. Energy budget (estimated within limits)
// 3. C-core packet serialization (each step is executable)
func ValidatePlan(plan *Plan, budget CostEstimate) error {
	// Check conflicts
	for i, step := range plan.Steps {
		conflicts, ok := ConflictMatrix[step.OpCode]
		if !ok {
			continue
		}
		for j, other := range plan.Steps {
			if i == j {
				continue
			}
			for _, c := range conflicts {
				if other.OpCode == c {
					return fmt.Errorf("conflict: step %d (%s) incompatible with step %d (%s)", i, step.OpCode, j, other.OpCode)
				}
			}
		}
	}

	// Check budget
	if plan.EstimatedCost.Tokens > budget.Tokens {
		return fmt.Errorf("token budget exceeded: %d > %d", plan.EstimatedCost.Tokens, budget.Tokens)
	}

	// Validate each step can be serialized to C-core packet
	for i, step := range plan.Steps {
		pkt, err := cgo.PacketFromToolCall(step.OpCode, step.Arguments)
		if err != nil {
			return fmt.Errorf("step %d (%s) not executable: %w", i, step.OpCode, err)
		}
		if pkt.Opcode == "" {
			return fmt.Errorf("step %d (%s) produced empty packet", i, step.OpCode)
		}
	}

	plan.Status = "validated"
	return nil
}

// GeneratePlanFromGoal uses LLM + mesh context to produce a likely plan.
// This is a stub: real implementation would call LLM with tools list.
func GeneratePlanFromGoal(goal string, availableTools []ToolSchema) (*Plan, error) {
	// Placeholder: in production, this sends goal + tools to LLM
	// LLM returns JSON plan → parse → validate
	return &Plan{
		ID:   fmt.Sprintf("plan-%d", time.Now().Unix()),
		Goal: goal,
		Steps: []PlanStep{},
		Status: "pending",
	}, nil
}

// ToolSchema is the minimal info needed for plan generation.
type ToolSchema struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}
