package orchestrator

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Mayveskii/Mimic/internal/cgo"
	"github.com/Mayveskii/Mimic/internal/model"
)

// Plan describes a multi-step operation sequence generated by an LLM.
type Plan struct {
	ID            string       `json:"id"`
	Goal          string       `json:"goal"`
	Steps         []PlanStep   `json:"steps"`
	EstimatedCost CostEstimate `json:"estimated_cost"`
	Status        string       `json:"status"` // pending | validated | executing | completed | failed
}

type PlanStep struct {
	OpCode     string                 `json:"opcode"`
	Arguments  map[string]interface{} `json:"arguments"`
	Invariant  string                 `json:"invariant"` // expected outcome
	RollbackOp string                 `json:"rollback_op,omitempty"`
}

type CostEstimate struct {
	Tokens  int `json:"tokens"`
	TimeUs  int `json:"time_us"`
	MemoryB int `json:"memory_b"`
}

// ConflictMatrix defines which operations cannot run together.
// Borrowed from embryo/pkg/do/
var ConflictMatrix = map[string][]string{
	"SYS_EXEC":     {"BUILD_COMPILE", "BUILD_DEPLOY", "PROC_SPAWN"},
	"BUILD_DEPLOY": {"BUILD_COMPILE", "SYS_EXEC"},
	"PROC_KILL":    {"PROC_SPAWN"},
	"GIT_COMMIT":   {"GIT_RESET", "GIT_CHECKOUT"},
	"FILE_EDIT":    {"FILE_EDIT"}, // same-file sequential only
}

// ValidatePlan checks a generated plan against:
// 1. Conflict matrix (no incompatible operations in parallel)
// 2. Energy budget (estimated within limits)
// 3. C-core packet serialization (each step is executable)
func ValidatePlan(plan *Plan, budget CostEstimate) error {
	// Check conflicts
	for i, step := range plan.Steps {
		conflicts, ok := ConflictMatrix[step.OpCode]
		if !ok {
			continue
		}
		for j, other := range plan.Steps {
			if i == j {
				continue
			}
			for _, c := range conflicts {
				if other.OpCode == c {
					return fmt.Errorf("conflict: step %d (%s) incompatible with step %d (%s)", i, step.OpCode, j, other.OpCode)
				}
			}
		}
	}

	// Check budget
	if plan.EstimatedCost.Tokens > budget.Tokens {
		return fmt.Errorf("token budget exceeded: %d > %d", plan.EstimatedCost.Tokens, budget.Tokens)
	}

	// Validate each step can be serialized to C-core packet
	for i, step := range plan.Steps {
		pkt, err := cgo.PacketFromToolCall(step.OpCode, step.Arguments)
		if err != nil {
			return fmt.Errorf("step %d (%s) not executable: %w", i, step.OpCode, err)
		}
		if pkt.Opcode == "" {
			return fmt.Errorf("step %d (%s) produced empty packet", i, step.OpCode)
		}
	}

	plan.Status = "validated"
	return nil
}

// GeneratePlanFromGoal uses LLM + mesh context to produce a likely plan.
// It returns either a direct answer (no steps) or a plan of tool calls.
func GeneratePlanFromGoal(ctx context.Context, caller model.Caller, goal string, availableTools []model.ToolSchema, context string) (*Plan, error) {
	if caller == nil {
		return &Plan{Goal: goal, Status: "pending"}, nil
	}

	system := "You are Mimic, an autonomous engineering agent. " +
		"You have access to deterministic tools. " +
		"For the user's intent, either answer directly (if read-only) or emit a JSON plan with opcode steps. " +
		"Each step must have fields: opcode, arguments, invariant. " +
		"Prefer safe, reversible operations. Validate before destructive ops."

	messages := []model.Message{
		{Role: "system", Content: system + "\n\n" + context},
		{Role: "user", Content: goal},
	}

	req := model.ChatRequest{
		Model:       "",
		Messages:    messages,
		Tools:       availableTools,
		ToolChoice:  "auto",
		Temperature: 0.1,
	}

	res, err := caller.Call(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("model call failed: %w", err)
	}

	plan := &Plan{
		ID:     fmt.Sprintf("plan-%d", time.Now().Unix()),
		Goal:   goal,
		Status: "pending",
	}

	if len(res.Response.Choices) == 0 {
		return plan, nil
	}

	choice := res.Response.Choices[0].Message

	// If the model wants tool calls, convert them into plan steps.
	if len(choice.ToolCalls) > 0 {
		for _, tc := range choice.ToolCalls {
			var args map[string]interface{}
			if tc.Function.Arguments != "" {
				if err := json.Unmarshal([]byte(tc.Function.Arguments), &args); err != nil {
					return nil, fmt.Errorf("tool call arguments not valid JSON: %w", err)
				}
			}
			plan.Steps = append(plan.Steps, PlanStep{
				OpCode:    tc.Function.Name,
				Arguments: args,
				Invariant: "tool executed successfully",
			})
		}
		return plan, nil
	}

	// Otherwise try to parse the content as a JSON plan.
	content := choice.Content
	if content != "" {
		var parsed Plan
		if err := json.Unmarshal([]byte(content), &parsed); err == nil && len(parsed.Steps) > 0 {
			parsed.ID = plan.ID
			parsed.Goal = goal
			parsed.Status = "pending"
			return &parsed, nil
		}
	}

	// Direct answer with no steps.
	return plan, nil
}
